version: "3.6"
services:
  rabbitmq:
  image: via/rabbitmq:3.9.13-management
  hostname: "{{.Node.Hostname}}"
  environment:
    - RABBITMQ_DEFAULT_USER=admin
    - RABBITMQ_DEFAULT_PASS=Passw0rd
    - RABBITMQ_ERLANG_COOKIE="MY-SECRET-KEY-123"
  networks:
    - rabbitmq-net
    - prod
  volumes:
    - rabbitmq-data:/var/lib/rabbitmq
    - "/home/ubuntu/rabbitmq/conf/enabled_plugins:/etc/rabbitmq/enabled_plugins"
    - "/home/ubuntu/rabbitmq/conf/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf"
  deploy:
    mode: global
    placement:
      constraints: [node.labels.rabbitmq == true]
networks:
  rabbitmq-net:
  prod:
    external: true
volumes:
  rabbitmq-data:
